name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validar sintaxe do script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verificar sintaxe do status-check.sh
        run: bash -n status-check.sh

  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Executar testes
        run: |
          echo "Running tests ..."
          sleep 1
          exit 0

  package:
    name: Empacotar Aplicação
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Criar artefato report.zip
        run: |
          mkdir -p reports
          echo "Relatório gerado em $(date)" > reports/report.txt
          zip -r report.zip reports/

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
