name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    name: Validar sintaxe do script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verificar sintaxe do status-check.sh
        run: |
          if bash -n status-check.sh; then
            echo "::notice::Sintaxe OK"
          else
            echo "::error::Erro de sintaxe no status-check.sh"
            exit 1
          fi

  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Executar testes
        run: |
          echo "Running tests ..."
          sleep 1
          echo "::warning::Nenhum teste automatizado foi encontrado."
          exit 0

  package:
    name: Empacotar Aplicação
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Criar artefato report.zip
        run: |
          mkdir -p reports
          echo "Relatório gerado em $(date)" > reports/report.txt
          zip -r report.zip reports/

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Gerar summary do job
        run: |
          echo "### Resumo do Job" >> $GITHUB_STEP_SUMMARY
          echo "- Ambiente: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Resultado: Sucesso" >> $GITHUB_STEP_SUMMARY
          echo "- [Baixar artefato](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
