name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify status check script syntax
        run: bash -n status-check.sh

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests ..."
          sleep 1
          exit 0

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Create artifact report.zip
        run: |
          mkdir -p reports
          echo "Relatório gerado em $(date)" > reports/report.txt
          zip -r report.zip reports/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
