name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Simular deploy
        run: echo "Deploying to ${{ vars.PROD_DOMAIN }}"
